// Generated by opengeodeweb-microservice-generate, do not edit.
import type json from "./vease_back_schemas.json";

export interface PackagesVersionsParams {
}

export interface PackagesVersionsResponse {
    packages_versions: PackagesVersion[];
}

export interface PackagesVersion {
    package: string;
    version: string;
}

export interface MicroserviceVersionParams {
}

export interface MicroserviceVersionResponse {
    microservice_version: string;
}

export interface HealthcheckParams {
}

export interface HealthcheckResponse {
    message: string;
}

export interface ErrorResponse {
    code:        number;
    description: string;
    name:        string;
}

// `__params` and `__response` only exist at type level, to infer request/response types from a schema.
// A type alias (not an interface) keeps the implicit index signature of the JSON type it is intersected with.
export type TypedSchema<Params, Response> = {
  readonly __params?: Params;
  readonly __response?: Response;
};

export interface Schemas {
  readonly vease_back: {
    readonly packages_versions: (typeof json)["vease_back"]["packages_versions"] & TypedSchema<PackagesVersionsParams, PackagesVersionsResponse>;
    readonly microservice_version: (typeof json)["vease_back"]["microservice_version"] & TypedSchema<MicroserviceVersionParams, MicroserviceVersionResponse>;
    readonly healthcheck: (typeof json)["vease_back"]["healthcheck"] & TypedSchema<HealthcheckParams, HealthcheckResponse>;
  };
}

declare const schemas: Schemas;
export default schemas;
