name: CICD

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: Geode-solutions/actions/get-release@master
        id: wheels
        with:
          repository: OpenGeodeWeb-Back
          file: ".whl"
          token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref_name }}
      - name: Wheels from Github
        run: |
          wheels=$(echo "${{ steps.wheels.outputs.path }}" | sed 's/\;/\ /g')
          echo $wheels
          if [ -n "$wheels" ]; then 
            pip install --no-deps $wheels
          fi
      - name: Test
        run: |
          pip install -r requirements.txt
          # pip install .
          # pip install pytest
          # pytest

  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Create Release
        uses: actions/github-script@v7
        with:
          script: |
            const refs = await github.rest.git.listMatchingRefs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/${{ github.head_ref }}-tag"
            })
            console.log(refs)
            if(refs.data.length > 0) {
              console.log("Tag already exists, skipping release")
              return
            }
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ github.head_ref }}-tag",
              name: "${{ github.head_ref }}",
              prerelease: true,
              target_commitish: "${{ github.head_ref }}"
            })
        env:
          GH_TOKEN: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    needs: release
    # if: github.ref == 'refs/heads/next' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        id: semantic-release
        with:
          github_token: ${{ secrets.TOKEN }}
      - name: Build
        run: |
          sed -i 's/version = "[0-9]*\.[0-9]*\.[0-9]*\(-rc\.[0-9]*\)\?"/version = "0.0.0"/' pyproject.toml
          python3 -m pip install --upgrade build
          python3 -m build
      # - name: Upload PYPI
      #   if: steps.semantic-release.outputs.released == 'true'
      #   run: |
      #     python3 -m pip install twine==6.0.1
      #     python3 -m twine upload --repository pypi dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
      # - name: Setup NODE
      #   uses: actions/setup-node@v3
      #   with:
      #     registry-url: "https://registry.npmjs.org"
      #     node-version: "20.x"
      # - name: Upload NPM
      #   if: steps.semantic-release.outputs.released == 'true'
      #   run: |
      #     pwd
      #     cd ${{ github.workspace }}
      #     npm i
      #     npm run json
      #     jq '.version="${{steps.semantic-release.outputs.version}}"' package.json > temp && mv temp package.json
      #     cat package.json
      #     npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Merge master -> next
      #   if: github.ref == 'refs/heads/master'
      #   uses: devmasx/merge-branch@master
      #   with:
      #     type: now
      #     from_branch: master
      #     target_branch: next
      #     github_token: ${{ secrets.TOKEN }}

  # docker-build-squash-push:
  #   uses: Geode-solutions/actions/.github/workflows/docker-build-squash-push.yml@master
  #   if: github.ref == 'refs/heads/next' || github.ref == 'refs/heads/master'
  #   with:
  #     image_name: "vease-back"
  #     tag: ${{ github.ref_name }}
  #   secrets:
  #     TOKEN: ${{secrets.GITHUB_TOKEN}}
